version: "3.7"

services:
  db:
    image: bitnami/mongodb:4.2.2
    environment:
      MONGODB_USERNAME: linden_honey
      MONGODB_PASSWORD: linden_honey
      MONGODB_DATABASE: linden_honey
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - db_data:/bitnami

  app:
    image: lindenhoney/linden-honey-api-go:latest
    build: .
    depends_on:
      - db
    environment:
      DB_URL: mongodb://linden_honey:linden_honey@db:27017/linden_honey
    ports:
      - 8080:80

volumes:
  db_data:
